apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bcc
  name: bcc
  labels:
    app: bcc
spec:
  selector:
    matchLabels:
      app: bcc
  template:
    metadata:
      labels:
        app: bcc
        name: bcc
    spec:
      containers:
        - name: bcc
          image: unnagirirao/abcd/bcc
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 1234
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        