apiVersion: v1
kind: Service
metadata:
  namespace: bcc
  labels:
    app: bcc
  name: bcc
spec:
  ports:
  
    - protocol: TCP
      port: 1234
      targetPort: 1234
   
   
  selector:
    app: bcc
  type: ClusterIP
